from SPPCompiler.SemanticAnalysis.ASTs import LoopExpressionConditionBooleanAst, LoopExpressionConditionIterableAst

type LoopExpressionConditionAst = LoopExpressionConditionBooleanAst | LoopExpressionConditionIterableAst

__all__ = ["LoopExpressionConditionAst"]
